In [1]:
import collections, numpy as np, pandas as pd, matplotlib, matplotlib.pyplot as plt, seaborn as sns
import floweaver, ipysankeywidget
%load_ext autoreload
%autoreload 2
from af2genomics import *

In [2]:
df_ = pd.read_csv(workpath('24.02.06_Sankey/clinvar_subset.tsv'), delim_whitespace=True)#, nrows=10)
df_['variant_id'] = df_.apply(lambda r: f'{r.gene}/{r.wildType}{r.position}{r.mutatedType}', axis=1)
printlen(df_, 'ClinVar variants')
df_

<module>: 351,349 ClinVar variants

,gene,position,wildType,mutatedType,eve,pred_ddg,plddt,sasa,pocketscore,pocketrank,interface,interface_strict,freq,xref,significance,association,clintype,variant_id
0,A0A096LP55,53,Y,C,0.000000,1.371100,94.93,51,23.991271,2,-99.000000,-99.000000,0.146400,"ClinVar,ESP,1000Genomes,dbSNP,ClinGen,TOPMed,E...",Benign,UNK,0,A0A096LP55/Y53C
1,A0AUZ9,968,D,G,0.002857,-99.000000,-99.00,-99,-99.000000,-99,-99.000000,-99.000000,0.003594,"ExAC,gnomAD,ClinGen,1000Genomes,TOPMed,ClinVar...",Benign,UNK,0,A0AUZ9/D968G
2,A0AVI2,687,T,A,0.000000,1.007870,81.14,51,95.817995,4,-99.000000,-99.000000,0.495200,"ExAC,gnomAD,ESP,ClinGen,1000Genomes,TOPMed,Uni...",Benign,UNK,0,A0AVI2/T687A
3,A0AVI2,687,T,S,0.000000,0.301708,81.14,51,95.817995,4,-99.000000,-99.000000,0.495200,"ExAC,gnomAD,ESP,ClinGen,1000Genomes,TOPMed",Benign,UNK,0,A0AVI2/T687S
4,A0AVK6,231,I,T,0.000000,-99.000000,-99.00,-99,-99.000000,-99,-99.000000,-99.000000,0.000599,"ExAC,gnomAD,ClinGen,1000Genomes,TOPMed,ClinVar...",Likely-benign,UNK,0,A0AVK6/I231T
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351344,Q9Y6X9,1002,V,L,0.000327,-1.099150,86.06,0,-99.000000,-99,0.729853,0.729853,-99.000000,"TOPMed,ExAC,gnomAD,ClinGen",Variant-of-uncertain-significance,UNK,2,Q9Y6X9/V1002L
351345,Q9Y6X9,1002,V,M,0.000327,-1.317830,86.06,0,-99.000000,-99,0.729853,0.729853,-99.000000,"ClinVar,TOPMed,ExAC,ClinGen,dbSNP,gnomAD",Variant-of-uncertain-significance,Charcot-Marie-Tooth-disease-axonal-type-2Z,2,Q9Y6X9/V1002M
351346,Q9Y6X9,1010,E,Q,0.874315,-0.464535,68.80,30,-99.000000,-99,0.729853,-99.000000,-99.000000,"ClinVar,TOPMed,ClinGen,dbSNP,gnomAD",Variant-of-uncertain-significance,Charcot-Marie-Tooth-disease-axonal-type-2Z,2,Q9Y6X9/E1010Q
351347,Q9Y6Z7,176,C,W,0.973517,30.642100,98.37,0,35.821039,1,0.413874,-99.000000,-99.000000,"dbSNP,UniProt","Likely-pathogenic,Pathogenic",3MC-syndrome-3-(3MC3),1,Q9Y6Z7/C176W
351348,Q9Y6Z7,179,R,W,0.758298,-0.283732,96.30,52,29.363653,2,0.413874,0.413874,0.002995,"ClinVar,TOPMed,ExAC,ESP,ClinGen,cosmic-curated...",Likely-benign,UNK,0,Q9Y6Z7/R179W

In [3]:
def clinvar_label_(clintype):
    if clintype == 0:
        return 'Benign'
    elif clintype == 1:
        return 'Pathogenic'
    elif clintype == 2:
        return 'VUS'

df_['clinvar_label'] = df_['clintype'].map(clinvar_label_)
print(df_['clinvar_label'].value_counts())
df_

VUS           245153
Benign         61119
Pathogenic     45077
Name: clinvar_label, dtype: int64

,gene,position,wildType,mutatedType,eve,pred_ddg,plddt,sasa,pocketscore,pocketrank,interface,interface_strict,freq,xref,significance,association,clintype,variant_id,clinvar_label
0,A0A096LP55,53,Y,C,0.000000,1.371100,94.93,51,23.991271,2,-99.000000,-99.000000,0.146400,"ClinVar,ESP,1000Genomes,dbSNP,ClinGen,TOPMed,E...",Benign,UNK,0,A0A096LP55/Y53C,Benign
1,A0AUZ9,968,D,G,0.002857,-99.000000,-99.00,-99,-99.000000,-99,-99.000000,-99.000000,0.003594,"ExAC,gnomAD,ClinGen,1000Genomes,TOPMed,ClinVar...",Benign,UNK,0,A0AUZ9/D968G,Benign
2,A0AVI2,687,T,A,0.000000,1.007870,81.14,51,95.817995,4,-99.000000,-99.000000,0.495200,"ExAC,gnomAD,ESP,ClinGen,1000Genomes,TOPMed,Uni...",Benign,UNK,0,A0AVI2/T687A,Benign
3,A0AVI2,687,T,S,0.000000,0.301708,81.14,51,95.817995,4,-99.000000,-99.000000,0.495200,"ExAC,gnomAD,ESP,ClinGen,1000Genomes,TOPMed",Benign,UNK,0,A0AVI2/T687S,Benign
4,A0AVK6,231,I,T,0.000000,-99.000000,-99.00,-99,-99.000000,-99,-99.000000,-99.000000,0.000599,"ExAC,gnomAD,ClinGen,1000Genomes,TOPMed,ClinVar...",Likely-benign,UNK,0,A0AVK6/I231T,Benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
351344,Q9Y6X9,1002,V,L,0.000327,-1.099150,86.06,0,-99.000000,-99,0.729853,0.729853,-99.000000,"TOPMed,ExAC,gnomAD,ClinGen",Variant-of-uncertain-significance,UNK,2,Q9Y6X9/V1002L,VUS
351345,Q9Y6X9,1002,V,M,0.000327,-1.317830,86.06,0,-99.000000,-99,0.729853,0.729853,-99.000000,"ClinVar,TOPMed,ExAC,ClinGen,dbSNP,gnomAD",Variant-of-uncertain-significance,Charcot-Marie-Tooth-disease-axonal-type-2Z,2,Q9Y6X9/V1002M,VUS
351346,Q9Y6X9,1010,E,Q,0.874315,-0.464535,68.80,30,-99.000000,-99,0.729853,-99.000000,-99.000000,"ClinVar,TOPMed,ClinGen,dbSNP,gnomAD",Variant-of-uncertain-significance,Charcot-Marie-Tooth-disease-axonal-type-2Z,2,Q9Y6X9/E1010Q,VUS
351347,Q9Y6Z7,176,C,W,0.973517,30.642100,98.37,0,35.821039,1,0.413874,-99.000000,-99.000000,"dbSNP,UniProt","Likely-pathogenic,Pathogenic",3MC-syndrome-3-(3MC3),1,Q9Y6Z7/C176W,Pathogenic
351348,Q9Y6Z7,179,R,W,0.758298,-0.283732,96.30,52,29.363653,2,0.413874,0.413874,0.002995,"ClinVar,TOPMed,ExAC,ESP,ClinGen,cosmic-curated...",Likely-benign,UNK,0,Q9Y6Z7/R179W,Benign

In [4]:
def pathogenicity_label_(eve):
    if eve < .4:
        return 'Pred. benign'
    elif eve >= .7:
        return 'Pred. pathogenic'
    else:
        return 'Pred. ambigous'

#df_['pathogenicity_label'] = df_['eve'].map(pathogenicity_label_)
#df_['pathogenicity_label'].value_counts()

df_ = df_.merge(query_missense(df_['variant_id'])[['variant_id', 'am_pathogenicity', 'am_class']], on='variant_id').reset_index(drop=True)

In [5]:
def read_pockets_resid():
    # Pockets, one per 
    #Q96EK7-F1      157
    cols_ = ['uniprot_id', 'struct_id', 'pocket_id', 'pocket_resid', 'pocket_score_combined_scaled']
    q_ = 'pocket_score_combined_scaled >= 900'
    return read_pockets().query(q_).explode('pocket_resid')[cols_].sort_values('pocket_score_combined_scaled', ascending=False).groupby(['uniprot_id', 'pocket_resid'])\
        .head(1)#.query('struct_id == "Q96EK7-F1" & pocket_resid == 157')

df_ = df_.merge(read_pockets_resid(), left_on=['gene', 'position'], right_on=['uniprot_id', 'pocket_resid'], how='left')

In [6]:
df_

,gene,position,wildType,mutatedType,eve,pred_ddg,plddt,sasa,pocketscore,pocketrank,...,clintype,variant_id,clinvar_label,am_pathogenicity,am_class,uniprot_id,struct_id,pocket_id,pocket_resid,pocket_score_combined_scaled
0,A0A096LP55,53,Y,C,0.000000,1.371100,94.93,51,23.991271,2,...,0,A0A096LP55/Y53C,Benign,0.0399,benign,NaN,NaN,NaN,NaN,NaN
1,A0AUZ9,968,D,G,0.002857,-99.000000,-99.00,-99,-99.000000,-99,...,0,A0AUZ9/D968G,Benign,0.0779,benign,NaN,NaN,NaN,NaN,NaN
2,A0AVI2,687,T,A,0.000000,1.007870,81.14,51,95.817995,4,...,0,A0AVI2/T687A,Benign,0.0485,benign,A0AVI2,A0AVI2-F1,4.0,687,992.540853
3,A0AVI2,687,T,S,0.000000,0.301708,81.14,51,95.817995,4,...,0,A0AVI2/T687S,Benign,0.0790,benign,A0AVI2,A0AVI2-F1,4.0,687,992.540853
4,A0AVK6,231,I,T,0.000000,-99.000000,-99.00,-99,-99.000000,-99,...,0,A0AVK6/I231T,Benign,0.0777,benign,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332450,Q9Y6X9,1002,V,L,0.000327,-1.099150,86.06,0,-99.000000,-99,...,2,Q9Y6X9/V1002L,VUS,0.3442,ambiguous,NaN,NaN,NaN,NaN,NaN
332451,Q9Y6X9,1002,V,M,0.000327,-1.317830,86.06,0,-99.000000,-99,...,2,Q9Y6X9/V1002M,VUS,0.1495,benign,NaN,NaN,NaN,NaN,NaN
332452,Q9Y6X9,1010,E,Q,0.874315,-0.464535,68.80,30,-99.000000,-99,...,2,Q9Y6X9/E1010Q,VUS,0.8389,pathogenic,NaN,NaN,NaN,NaN,NaN
332453,Q9Y6Z7,176,C,W,0.973517,30.642100,98.37,0,35.821039,1,...,1,Q9Y6Z7/C176W,Pathogenic,0.9979,pathogenic,Q9Y6Z7,Q9Y6Z7-F1,1.0,176,922.019412
332454,Q9Y6Z7,179,R,W,0.758298,-0.283732,96.30,52,29.363653,2,...,0,Q9Y6Z7/R179W,Benign,0.4258,ambiguous,NaN,NaN,NaN,NaN,NaN

In [7]:
#df_models = read_ppi_reselect().query('pdockq > .5')#.query('afparams != "fd_rev"')#.query('interface_plddt > 90')
df_models = read_af2_human_interactions(pdockq=.5)
df_models

read_af2_human_interactions: 486,099 raw records from /cluster/work/beltrao/jjaenes/24.01.30_af2_human_interations/24.01.30_af2_human_interactions.tsv
read_af2_human_interactions: 485,410 after removing negatome-only interactions
read_af2_human_interactions: 24,099 after filtering for pdockq

,interaction_id,source,biogrid_nrecords,pair,afparams,interface_plddt,pdockq,pdockq_fd,pdockq2,clashes,...,residues1,protein2,chain2,residues2,pair1,pair2,pdb,biogrid_nrecords_max5,pdockq_bin,summary_source_top
0,A0A075B759_P0DN37,BioGRID:humap,0,A0A075B759_P0DN37,multimer1_rec10,77.0,0.54,0.181,0.04,0.0,...,"55,57,58,59,60,61,63,72,73,101,102,103,113,117...",P0DN37,B,"55,57,58,59,60,63,72,73,75,82,101,102,103,111,...",A0A075B759,P0DN37,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,0,>0.5,BioGRID
1,A0A096LP49_Q4VC12,BioGRID:huri,0,A0A096LP49_Q4VC12,fd_rev,70.0,0.56,0.342,NaN,2.0,...,"31,34,42,43,44,45,46,47,49,50,52,53,65,67,70,7...",A0A096LP49,B,"49,51,52,63,64,66,68,152,155,156,158,159,160,1...",A0A096LP49,Q4VC12,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,0,>0.5,BioGRID
2,A0A0B4J2A2_P0DN37,BioGRID:humap,0,A0A0B4J2A2_P0DN37,multimer1,78.0,0.56,0.228,0.04,0.0,...,"55,57,58,59,60,61,63,72,73,100,101,102,103,104...",P0DN37,B,"55,57,58,59,60,61,63,73,100,101,102,103,104,11...",A0A0B4J2A2,P0DN37,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,0,>0.5,BioGRID
3,A0A0B4J2D5_Q96EL3,intact,0,A0A0B4J2D5_Q96EL3,multimer1,92.0,0.60,0.328,0.52,0.0,...,"55,87,88,90,94,95,96,97,137,140,141,146,147,14...",Q96EL3,B,"20,22,23,24,25,31,34,35,53,54,55,56,57,58",A0A0B4J2D5,Q96EL3,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,0,>0.5,other
4,A0A140G945_P02489,huri,0,A0A140G945_P02489,fd_rev,80.0,0.53,0.460,NaN,0.0,...,"1,2,3,4,5,6,7,59,60,61,62,64,79,82,85,87,88,89...",A0A140G945,B,"1,2,3,4,5,6,7,8,59,60,61,62,63,64,76,79,82,85,...",A0A140G945,P02489,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,0,>0.5,other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24094,Q9Y617_Q9Y617,BioGRID:gtex:intact,1,Q9Y617_Q9Y617,multimer1,96.0,0.73,0.723,0.81,0.0,...,"4,5,7,9,13,14,15,16,17,19,22,23,25,26,27,29,30...",Q9Y617,B,"4,5,7,9,13,14,15,16,17,19,22,23,25,26,27,29,30...",Q9Y617,Q9Y617,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,1,>0.5,BioGRID
24095,Q9Y6A5_Q9Y6A5,intact,0,Q9Y6A5_Q9Y6A5,multimer1,76.0,0.68,0.682,0.11,0.0,...,"10,11,12,13,14,15,171,172,173,215,216,217,236,...",Q9Y6A5,B,"35,38,39,122,123,124,125,126,127,128,129,130,1...",Q9Y6A5,Q9Y6A5,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,0,>0.5,other
24096,Q9Y6B7_Q9Y6Q5,otar:string,0,Q9Y6B7_Q9Y6Q5,multimer1,86.0,0.73,0.674,0.45,0.0,...,"34,37,38,40,41,42,62,63,66,67,70,73,100,104,10...",Q9Y6Q5,B,"1,14,15,16,17,19,20,21,22,23,40,43,44,46,47,48...",Q9Y6B7,Q9Y6Q5,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,0,>0.5,string
24097,Q9Y6C2_Q9Y6C2,BioGRID:huri:intact,4,Q9Y6C2_Q9Y6C2,fd,57.0,0.53,0.497,NaN,0.0,...,"45,46,47,48,74,77,79,82,98,103,106,113,114,115...",Q9Y6C2,B,"37,63,79,82,98,103,106,113,114,116,141,142,143...",Q9Y6C2,Q9Y6C2,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,4,>0.5,BioGRID
24098,Q9Y6K9_Q9Y6K9,BioGRID:intact,20,Q9Y6K9_Q9Y6K9,multimer1,85.0,0.73,0.726,0.52,0.0,...,"7,10,11,13,14,16,50,51,54,55,57,58,61,62,64,65...",Q9Y6K9,B,"3,6,7,10,11,13,14,16,47,50,51,54,55,57,58,61,6...",Q9Y6K9,Q9Y6K9,/cluster/work/beltrao/jjaenes/23.12.06_ppi_res...,5,>0.5,BioGRID

In [8]:
# One entry per "interaction matrix" (dimer models = both; homomer models = 1)
cols_ = ['uniprot_id', 'ifresid']
q_ne_ = 'protein1 != protein2'
q_eq_ = 'protein1 == protein2'
df_interfaces = pd.concat([
    df_models.query(q_ne_).rename({'protein1': 'uniprot_id', 'residues1': 'ifresid',}, axis=1)[cols_],
    df_models.query(q_eq_).rename({'protein1': 'uniprot_id', 'residues1': 'ifresid',}, axis=1)[cols_],
    df_models.query(q_ne_).rename({'protein2': 'uniprot_id', 'residues2': 'ifresid',}, axis=1)[cols_],
], axis=0)
df_interfaces['ifresid'] = df_interfaces['ifresid'].map(parse_resid)
df_ifresid = df_interfaces.explode('ifresid').drop_duplicates(keep='first')

In [9]:
df_ = df_.merge(df_ifresid, left_on=['gene', 'position'], right_on=['uniprot_id', 'ifresid'], how='left')

In [27]:
def mechanistic_label_(r):
    if r.pred_ddg == -99:
        return 'Unassigned'
    elif r.pred_ddg > 2:
        return 'Stability'
    #elif r.interface >= .4:
    elif r.ifresid == r.ifresid:
        return 'Interface'
    elif r.pocket_id > 0:
        return 'Pockets'
    else:
        return 'Unassigned'

df_['mechanistic_label'] = df_.apply(mechanistic_label_, axis=1)
df_['mechanistic_label'].value_counts()

Unassigned    203584
Stability      64961
Pockets        37197
Interface      26713
Name: mechanistic_label, dtype: int64

In [28]:
cols_ = ['clinvar_label', 'am_class', 'mechanistic_label']
flows_ = df_[cols_].groupby(cols_).size().reset_index().rename({0: 'value',
    'clinvar_label': 'source',
    'am_class': 'type',
    'mechanistic_label': 'target',
}, axis=1)
flows_
#ipysankeywidget.SankeyWidget(links=flows_.to_dict('records'))

        source        type      target   value
0       Benign   ambiguous   Interface     405
1       Benign   ambiguous     Pockets     507
2       Benign   ambiguous   Stability     876
3       Benign   ambiguous  Unassigned    2888
4       Benign      benign   Interface    2672
5       Benign      benign     Pockets    4505
6       Benign      benign   Stability    2374
7       Benign      benign  Unassigned   36419
8       Benign  pathogenic   Interface     680
9       Benign  pathogenic     Pockets     986
10      Benign  pathogenic   Stability    2012
11      Benign  pathogenic  Unassigned    3335
12  Pathogenic   ambiguous   Interface     444
13  Pathogenic   ambiguous     Pockets     477
14  Pathogenic   ambiguous   Stability    1385
15  Pathogenic   ambiguous  Unassigned    1689
16  Pathogenic      benign   Interface     832
17  Pathogenic      benign     Pockets    1139
18  Pathogenic      benign   Stability    1163
19  Pathogenic      benign  Unassigned    5417
20  Pathogenic  pathogenic   Interface    3414
21  Pathogenic  pathogenic     Pockets    3717
22  Pathogenic  pathogenic   Stability   16469
23  Pathogenic  pathogenic  Unassigned    7892
24         VUS   ambiguous   Interface    2220
25         VUS   ambiguous     Pockets    3029
26         VUS   ambiguous   Stability    5749
27         VUS   ambiguous  Unassigned   13287
28         VUS      benign   Interface   10437
29         VUS      benign     Pockets   16387
30         VUS      benign   Stability   11408
31         VUS      benign  Unassigned  113360
32         VUS  pathogenic   Interface    5609
33         VUS  pathogenic     Pockets    6450
34         VUS  pathogenic   Stability   23525
35         VUS  pathogenic  Unassigned   19297

In [29]:
clinvar_part_ = floweaver.Partition.Simple('source', ['Benign', 'VUS', 'Pathogenic'])
#pathogenicity_part_ = floweaver.Partition.Simple('type', ['Pred. benign', 'Pred. ambigous', 'Pred. pathogenic'])
pathogenicity_part_ = floweaver.Partition.Simple('type', ['benign', 'ambiguous', 'pathogenic'])
mechanistic_part_ = floweaver.Partition.Simple('target', ['Unassigned', 'Stability', 'Interface', 'Pockets'])

nodes_ = {
    'clinvar_col': floweaver.ProcessGroup(selection=flows_['source'].unique().tolist(), title='Known annotations', partition=clinvar_part_),
    'pathogenicity_col': floweaver.Waypoint(partition=pathogenicity_part_, title='AlphaMissense'),
    'mechanistic_col': floweaver.ProcessGroup(selection=flows_['target'].unique().tolist(), title='Structural mechanisms', partition=mechanistic_part_),
}

#nodes_['mechanistic_col'].partition = floweaver.Partition.Simple('process', flows_['target'].unique().tolist())
#nodes_['mechanistic_col'].partition = floweaver.Partition.Simple('process', ['Unassigned', 'Stability', 'Interface', 'Pockets'])

ordering_ = [['clinvar_col'], ['pathogenicity_col'], ['mechanistic_col'],]

bundles_ = [floweaver.Bundle('clinvar_col', 'mechanistic_col', waypoints=['pathogenicity_col']),]

class AdhocScale_(floweaver.QuantitativeScale):
    # https://matplotlib.org/stable/gallery/color/named_colors.html#css-colors
    def get_color(self, link, value):
        if link.target == 'mechanistic_col^Unassigned':
            return matplotlib.colors.CSS4_COLORS['lightgrey']
        elif link.target == 'mechanistic_col^Stability':
            return matplotlib.colors.CSS4_COLORS['lightpink']
        elif link.target == 'mechanistic_col^Interface':
            return matplotlib.colors.CSS4_COLORS['yellow']
        elif link.target == 'mechanistic_col^Pockets':
            return matplotlib.colors.CSS4_COLORS['lightgreen']
        elif link.type == 'benign':
            return matplotlib.colors.CSS4_COLORS['lightblue']
        elif link.type == 'pathogenic':
            return matplotlib.colors.CSS4_COLORS['lightcoral']
        return matplotlib.colors.CSS4_COLORS['silver']

sdd_ = floweaver.SankeyDefinition(nodes_, bundles_, ordering_, flow_partition=pathogenicity_part_)
#floweaver.weave(sankey_definition=sdd_, dataset=flows_, palette=palette_).to_widget(width=600, height=400).auto_save_svg('clinvar_mechanisms.svg')
floweaver.weave(sankey_definition=sdd_, dataset=flows_, link_color=AdhocScale_('value')).to_widget(width=600, height=400).auto_save_svg('clinvar_mechanisms.svg')

SankeyWidget(groups=[{'id': 'clinvar_col', 'type': 'process', 'title': 'Known annotations', 'nodes': ['clinvar…